### ISSUE TITLE
new version LOBCAST launch time enquiry

### ISSUE THREAD

**Issue by erasmeyu** [matteoprata/LOBCAST#3]
Many thanks for your open source skeleton. That does help a lot.

I notice it's mentioned that 'a more stable version LOBCAST will be released soon.'

Could you please update the LOBCAST skeleton?

I can then publish my open source LOB forecasting model and add it into LOBCAST.

**Comment by LeonardoBerti00** [comment]
Sorry for the wait. We are currently working on it, in the next few days we will release the new updated version, thank you for your interest.

**Comment by erasmeyu** [comment]
Dear Leonardo,

*Many thanks for your reply and update. I have checked github for many
times, but haven't found the new version LOBCAST.*

*Looking forward to your new version LOBCAST. That does help a lot.*

*Best wishes*
*Yang Yu*

**Comment by LeonardoBerti00** [comment]
Hi Yang, the new version is out.
